services:
  postgresDB:
    image: postgres:17.2
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_crud
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - "5436:5432"