services:
  - type: web
    name: pokebingo-backend
    env: node
    nodeVersion: 18.17.0
    buildCommand: yarn install && yarn build
    startCommand: yarn start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: pokebingo-db
    databaseName: db_crud
    user: pokebingo_user
    plan: free 